apiVersion: v1
kind: Service
metadata:
  name: ubuntu-nginx-pag-default-ser
  labels:
     app: ubuntu-nginx-pag-default-pod
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
     app: ubuntu-nginx-pag-default-pod
